version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maria
      MYSQL_DATABASE: healthdb
      MYSQL_USER: gym
      MYSQL_PASSWORD: gym
    ports:
      - "3306:3306"
    networks:
      - msanet
    volumes:
      - mariadb-data:/var/lib/mysql

  app:
    image: huns1/thridprojectback:0.1
    container_name: myhealth
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: healthdb
      DB_USERNAME: gym
      DB_PASSWORD: gym
    networks:
      - msanet

networks:
  msanet:

volumes:
  mariadb-data: