name: Build and Push All Service Images

on:
  push:
    branches: [main, dev]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # backend
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./ThirdprojectBack
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/health-ai:backend-v1

      # frontend
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/health-ai:frontend-v1

      # ai server
      - name: Build and push AI server image
        uses: docker/build-push-action@v5
        with:
          context: ./ai
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/health-ai:ai-v1
      # Deploy to EC2 via SSH
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/health-ai
            docker compose pull
            docker compose up -d
            docker image prune -a